@startuml
class ObjectSpin {
    + SpinSpeed : float = 5
    + RotationRange : int = 15
}
enum MotionType {
    Rotation,
    BackAndForth,
    Translation,
}
MonoBehaviour <|-- ObjectSpin
ObjectSpin --> "Motion" MotionType
ObjectSpin +-- MotionType
@enduml
